# Generated by Django 4.1.7 on 2023-02-21 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0002_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_option', models.CharField(max_length=50, verbose_name='Input Option')),
                ('input_code', models.CharField(max_length=50, verbose_name='Input Code')),
                ('leave_code', models.CharField(max_length=50, verbose_name='Leave Code')),
                ('no_of_days', models.PositiveIntegerField(verbose_name='No. Of Days')),
                ('accrued', models.BooleanField(verbose_name='Accrued')),
                ('automatically_roll_over', models.BooleanField(verbose_name='Automatically Roll Over')),
                ('transaction_date', models.DateField(verbose_name='Transaction Date')),
                ('no_series', models.CharField(max_length=50, verbose_name='No. Series')),
                ('posted', models.BooleanField(verbose_name='Posted')),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignments',
            },
        ),
        migrations.CreateModel(
            name='LeavePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=200, verbose_name='Employee Name')),
                ('leave_code', models.CharField(max_length=50, verbose_name='Leave Code')),
                ('leave_description', models.CharField(max_length=50, verbose_name='Leave Description')),
                ('no_of_planned_days', models.PositiveIntegerField(verbose_name='No. Of Planned Days')),
                ('start_date', models.DateField(auto_now=True, verbose_name='Start Date')),
                ('end_date', models.DateField(auto_now=True, verbose_name='End Date')),
                ('department_name', models.CharField(max_length=50, verbose_name='Department Name')),
                ('no_series', models.CharField(max_length=50, verbose_name='No. Series')),
                ('transaction_date', models.DateField(auto_now=True, verbose_name='Transaction Date')),
                ('posted', models.BooleanField(verbose_name='Posted')),
            ],
            options={
                'verbose_name': 'Leave Plan',
                'verbose_name_plural': 'Leave Plans',
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=50, verbose_name='No.')),
                ('emp_name', models.CharField(max_length=50, verbose_name='Employee Name')),
                ('contact_address', models.CharField(blank=True, max_length=50, null=True, verbose_name='Contact Text')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Phone No.')),
                ('leave_description', models.TextField(verbose_name='Leave Description')),
                ('total_leave_days', models.PositiveIntegerField(verbose_name='Total Leave Days')),
                ('outstanding_leave_days', models.PositiveIntegerField(verbose_name='Outstanding Leave Days')),
                ('no_of_days_requested', models.PositiveIntegerField(verbose_name='No. Of Days Requested')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('request_status', models.CharField(choices=[('APPROVED', 'Approved'), ('DEFERRED', 'Deferred'), ('REJECTED', 'Rejected')], max_length=50, verbose_name='Request Status')),
                ('deferred_reason', models.TextField(verbose_name='Deferred Reason')),
                ('transaction_date', models.DateField(verbose_name='Transaction')),
                ('no_series', models.CharField(max_length=100, verbose_name='No. Series')),
                ('relieving_officer_no', models.CharField(max_length=50, verbose_name='Relieving Officer No.')),
                ('relieving_officer_name', models.CharField(max_length=150, verbose_name="Relieving Officer's Name")),
                ('posted', models.BooleanField(verbose_name='Posted')),
            ],
            options={
                'verbose_name': 'Leave Request',
                'verbose_name_plural': 'Leave Requests',
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Code')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('job_level_code', models.CharField(max_length=50, verbose_name='Job Level Code')),
                ('no_of_days', models.PositiveIntegerField(verbose_name='No. Of Days')),
                ('accrued', models.BooleanField(verbose_name='Accrued')),
                ('automatically_roll_over', models.BooleanField(verbose_name='Automatically')),
                ('blocked', models.BooleanField(verbose_name='Blocked')),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.job', verbose_name='Job Title')),
            ],
            options={
                'verbose_name': 'Policy',
                'verbose_name_plural': 'Policies',
            },
        ),
        migrations.CreateModel(
            name='LeaveTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=50, verbose_name='No.')),
                ('emp_name', models.CharField(max_length=50, verbose_name='Employee Name')),
                ('contact_address', models.CharField(blank=True, max_length=50, null=True, verbose_name='Contact Text')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Phone No.')),
                ('leave_description', models.TextField(verbose_name='Leave Description')),
                ('total_leave_days', models.PositiveIntegerField(verbose_name='Total Leave Days')),
                ('outstanding_leave_days', models.PositiveIntegerField(verbose_name='Outstanding Leave Days')),
                ('no_of_days_requested', models.PositiveIntegerField(verbose_name='No. Of Days Requested')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('request_status', models.CharField(choices=[('APPROVED', 'Approved'), ('DEFERRED', 'Deferred'), ('REJECTED', 'Rejected')], max_length=50, verbose_name='Request Status')),
                ('deferred_reason', models.TextField(verbose_name='Deferred Reason')),
                ('transaction_date', models.DateField(verbose_name='Transaction')),
                ('no_series', models.CharField(max_length=100, verbose_name='No. Series')),
                ('relieving_officer_no', models.CharField(max_length=50, verbose_name='Relieving Officer No.')),
                ('relieving_officer_name', models.CharField(max_length=150, verbose_name="Relieving Officer's Name")),
                ('posted', models.BooleanField(verbose_name='Posted')),
                ('reason_recall', models.BooleanField(blank=True, null=True, verbose_name='Recalled')),
                ('reason_for_recall', models.CharField(max_length=100, verbose_name='Reason For Recall')),
                ('approved_from_deferred', models.BooleanField(verbose_name='Approved From Deferred')),
                ('recall_amount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Recall Amount')),
                ('department_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.department', verbose_name='Department')),
                ('emp_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='Employee Code')),
                ('job_title_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.job', verbose_name='Job Title Code')),
                ('leave_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave.policy', verbose_name='Leave Code')),
            ],
            options={
                'verbose_name': 'Leave Transaction',
                'verbose_name_plural': 'Leave Transactions',
            },
        ),
    ]
