# Generated by Django 4.2 on 2023-05-02 16:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Code')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
                ('max_number_of_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Max Number Of Days')),
                ('staff_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.staffcategory')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='From Date')),
                ('no_of_days_requested', models.PositiveIntegerField(verbose_name='No Of Days Requested')),
                ('job_description', models.CharField(blank=True, max_length=150, null=True, verbose_name='Job Description')),
                ('job_title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Job Title')),
                ('employee_unit', models.CharField(blank=True, max_length=80, null=True, verbose_name='Employee Unit')),
                ('employee_branch', models.CharField(blank=True, max_length=150, null=True, verbose_name='Employee Branch')),
                ('employee_level', models.CharField(blank=True, max_length=50, null=True, verbose_name='Employee Level')),
                ('date_applied', models.DateField(default=django.utils.timezone.now, verbose_name='Date Applied')),
                ('status', models.CharField(blank=True, max_length=150, null=True, verbose_name='Status')),
                ('hod_status', models.CharField(blank=True, max_length=150, null=True, verbose_name='HOD Status')),
                ('hod_remarks', models.CharField(blank=True, max_length=250, null=True, verbose_name='HOD Remarks')),
                ('relieving_officer_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Relieving Officer Name')),
                ('hod_remarks_date', models.CharField(blank=True, null=True, verbose_name='HOD Remarks Date')),
                ('hr_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='HR Status')),
                ('hr_remarks', models.CharField(blank=True, max_length=50, null=True, verbose_name='HR Remarks')),
                ('hr_remarks_date', models.CharField(blank=True, null=True, verbose_name='HR Remarks Date')),
                ('dep_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Department Code')),
                ('dep', models.CharField(blank=True, max_length=50, null=True, verbose_name='Department')),
                ('supporting_doc', models.TextField(blank=True, null=True, verbose_name='Supporting Document')),
                ('no_of_days_left', models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Days Left')),
                ('emp_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Employee Code')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='Employee')),
                ('leave_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leave.leavetype', verbose_name='Leave Type')),
            ],
            options={
                'verbose_name': 'Leave Request',
                'verbose_name_plural': 'Leave Requests',
            },
        ),
        migrations.CreateModel(
            name='LeavePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='From Date')),
                ('no_of_days_requested', models.PositiveIntegerField(verbose_name='No Of Days Requested')),
                ('job_description', models.CharField(blank=True, max_length=150, null=True, verbose_name='Job Description')),
                ('job_title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Job Title')),
                ('employee_unit', models.CharField(blank=True, max_length=80, null=True, verbose_name='Employee Unit')),
                ('employee_branch', models.CharField(blank=True, max_length=150, null=True, verbose_name='Employee Branch')),
                ('employee_level', models.CharField(blank=True, max_length=50, null=True, verbose_name='Employee Level')),
                ('date_applied', models.DateField(default=django.utils.timezone.now, verbose_name='Date Applied')),
                ('status', models.CharField(blank=True, max_length=150, null=True, verbose_name='Status')),
                ('hod_status', models.CharField(blank=True, max_length=150, null=True, verbose_name='HOD Status')),
                ('hod_remarks', models.CharField(blank=True, max_length=250, null=True, verbose_name='HOD Remarks')),
                ('relieving_officer_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Relieving Officer Name')),
                ('hod_remarks_date', models.CharField(blank=True, null=True, verbose_name='HOD Remarks Date')),
                ('hr_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='HR Status')),
                ('hr_remarks', models.CharField(blank=True, max_length=50, null=True, verbose_name='HR Remarks')),
                ('hr_remarks_date', models.CharField(blank=True, null=True, verbose_name='HR Remarks Date')),
                ('dep_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Department Code')),
                ('dep', models.CharField(blank=True, max_length=50, null=True, verbose_name='Department')),
                ('supporting_doc', models.TextField(blank=True, null=True, verbose_name='Supporting Document')),
                ('no_of_days_left', models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Days Left')),
                ('emp_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Employee Code')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='Employee')),
                ('leave_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leave.leavetype', verbose_name='Leave Type')),
            ],
            options={
                'verbose_name': 'Leave Plan',
                'verbose_name_plural': 'Leave Plans',
            },
        ),
    ]
