# Generated by Django 4.1.7 on 2023-02-21 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0003_initial'),
        ('trainingapplication', '0001_initial'),
        ('employee', '0003_initial'),
        ('paygroup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User ID'),
        ),
        migrations.AddField(
            model_name='plan',
            name='course_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingapplication.course', verbose_name='Course Name'),
        ),
        migrations.AddField(
            model_name='plan',
            name='department_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.department', verbose_name='Department Name'),
        ),
        migrations.AddField(
            model_name='plan',
            name='organizer_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingapplication.organizers', verbose_name='Organizer Name'),
        ),
        migrations.AddField(
            model_name='plan',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User ID'),
        ),
        migrations.AddField(
            model_name='participants',
            name='course_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingapplication.course', verbose_name='Course Name'),
        ),
        migrations.AddField(
            model_name='participants',
            name='emp_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='Employee Name'),
        ),
        migrations.AddField(
            model_name='participants',
            name='paygroup_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paygroup.paygroup', verbose_name='PayGroup Code'),
        ),
        migrations.AddField(
            model_name='participants',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User ID'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='emp_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='Employee Name'),
        ),
        migrations.AddField(
            model_name='coursedetail',
            name='course_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingapplication.course', verbose_name='Course Code'),
        ),
        migrations.AddField(
            model_name='budget',
            name='emp_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='Employee Name'),
        ),
        migrations.AddField(
            model_name='budget',
            name='expense_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingapplication.expense', verbose_name='Expense Code'),
        ),
    ]
