version: '3.9'

services:
  web:
    build: .
    command: gunicorn config.wsgi:application -w 3 -b 0.0.0.0:8000
    # command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8080:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  
  db:
   image: postgres:14-alpine
   ports:
     - "5430:5432"
   restart: always
   volumes:
     - postgres_data:/var/lib/postgresql/data/
   env_file:
      - ./.env.dev.db

volumes:
  postgres_data:

