# Generated by Django 4.1.7 on 2023-02-21 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0002_initial'),
        ('employee', '0001_initial'),
        ('paygroup', '0001_initial'),
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePolicy',
            fields=[
                ('leaverequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='leave.leaverequest')),
                ('assignment_no', models.CharField(max_length=50, verbose_name='Assignment No.')),
                ('last_date_modified', models.DateField(verbose_name='Last Date Modified')),
                ('closed', models.BooleanField(verbose_name='Closed')),
            ],
            options={
                'verbose_name': 'Employee Policy',
                'verbose_name_plural': 'Employee Policies',
            },
            bases=('leave.leaverequest',),
        ),
        migrations.CreateModel(
            name='EmployeePromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_job_title', models.CharField(max_length=50, verbose_name='New Job Title')),
                ('current_salary_grade', models.CharField(max_length=100, verbose_name='Current Salary Grade')),
                ('new_salary_grade', models.CharField(max_length=100, verbose_name='New Salary Grade')),
                ('current_notch', models.PositiveIntegerField(verbose_name='Current Notch')),
                ('new_notch', models.PositiveIntegerField(verbose_name='New Notch')),
                ('current_basic_salary', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Current Basic Salary')),
                ('new_basic_salary', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='New Basic Salary')),
                ('comment', models.CharField(max_length=250, verbose_name='Comment')),
                ('transaction_date', models.DateField(verbose_name='Date')),
                ('no_series', models.CharField(max_length=50, verbose_name='No. Series')),
                ('posted', models.BooleanField(verbose_name='Posted')),
                ('effective_date', models.DateField(verbose_name='Effective Date')),
                ('current_job_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.job', verbose_name='Current Job')),
                ('department_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.department', verbose_name='Department Name')),
                ('emp_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='Employee Name')),
                ('paygroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paygroup.paygroup', verbose_name='Pay Group')),
            ],
            options={
                'verbose_name': 'Employee Promotion',
                'verbose_name_plural': 'Employee Promotions',
            },
        ),
    ]
