# Generated by Django 4.1.7 on 2023-02-21 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepromotion',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User ID'),
        ),
        migrations.AddField(
            model_name='employeepayreview',
            name='emp_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='Employee Name'),
        ),
        migrations.AddField(
            model_name='employeepayreview',
            name='job_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.job', verbose_name='Job Title'),
        ),
        migrations.AddField(
            model_name='employeepayreview',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User ID'),
        ),
        migrations.AddField(
            model_name='employeemedicals',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.department', verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='employeemedicals',
            name='emp_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='Employee Name'),
        ),
        migrations.AddField(
            model_name='employeemedicals',
            name='medical_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.medicalcodes', verbose_name='Medical Type'),
        ),
        migrations.AddField(
            model_name='employeemedicals',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User ID'),
        ),
        migrations.AddField(
            model_name='employeedisciplinaryactions',
            name='department_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.department', verbose_name='Department Name'),
        ),
        migrations.AddField(
            model_name='employeedisciplinaryactions',
            name='emp_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='Employee Name'),
        ),
        migrations.AddField(
            model_name='employeedisciplinaryactions',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User ID'),
        ),
        migrations.AddField(
            model_name='employeeappraisalresponse',
            name='appraisal_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisalno', to='employee.employeeappraisal', verbose_name='Employee Appraisal No'),
        ),
        migrations.AddField(
            model_name='employeeappraisal',
            name='emp_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_name', to='employee.employee', verbose_name='Employee Name'),
        ),
        migrations.AddField(
            model_name='employeeappraisal',
            name='job_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.job', verbose_name='Job Title'),
        ),
        migrations.AddField(
            model_name='employeeappraisal',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User ID'),
        ),
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
    ]
