# Generated by Django 4.1.7 on 2023-02-21 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0002_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupInsuranceBeneficiaries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=50, verbose_name='No.')),
                ('emp_code', models.CharField(max_length=50, verbose_name='Employee Code')),
                ('job_level', models.CharField(max_length=50, verbose_name='Job Level')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Amount')),
                ('transaction_date', models.DateField(auto_now=True, verbose_name='Transaction Date')),
                ('no_series', models.CharField(max_length=50, verbose_name='No. Series')),
                ('posted', models.BooleanField(verbose_name='Posted')),
                ('incident', models.TextField(verbose_name='Incident')),
                ('policy_code', models.CharField(max_length=50, verbose_name='Policy Code')),
                ('policy_type', models.CharField(max_length=50, verbose_name='Policy Type')),
                ('insurance_company', models.CharField(max_length=50, verbose_name='Insurance Company')),
            ],
            options={
                'verbose_name': 'Group Insurance Beneficiaries',
                'verbose_name_plural': 'Group Insurance Beneficiaries',
            },
        ),
        migrations.CreateModel(
            name='GroupLifeInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Code')),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
                ('telephone', models.CharField(max_length=50, verbose_name='Telephone')),
                ('contact_person', models.CharField(max_length=50, verbose_name='Contact Person')),
                ('type_of_policy', models.CharField(max_length=50, verbose_name='Type Of Policy')),
                ('premium', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Premium')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Amount')),
                ('date', models.DateField(auto_now=True, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Group Life Insurance',
                'verbose_name_plural': 'Group Life Insurances',
            },
        ),
        migrations.CreateModel(
            name='InsurancePremiumPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=50, verbose_name='No.')),
                ('insurance_type', models.CharField(choices=[('GROUP PERSONAL', 'Group Personal'), ("WORKMEN'S COMPENSATION", "Workmen's Compensation"), ('LIFE INSURANCE', 'Life Insurance'), ('FIRE & ALLIED PERILS', 'Fire & Allied Perils'), ('VEHICLE INSURANCE', 'Vehicle Insurance'), ('OTHERS', 'Others')], max_length=50, verbose_name='Insurance Type')),
                ('period_start_date', models.DateField(auto_now=True, verbose_name='Period Start Date')),
                ('period_end_date', models.DateField(auto_now=True, verbose_name='Period End Date')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Amount Paid')),
                ('payment_date', models.DateField(auto_now=True, verbose_name='Payment Date')),
                ('remarks', models.CharField(max_length=100, verbose_name='Remarks')),
                ('transaction_date', models.DateField(auto_now=True, verbose_name='Transaction Date')),
                ('no_series', models.CharField(max_length=50, verbose_name='No. Series')),
                ('posted', models.BooleanField(verbose_name='Posted')),
            ],
            options={
                'verbose_name': 'Insurance Premium Payments',
                'verbose_name_plural': 'Insurance Premium Payments',
            },
        ),
        migrations.CreateModel(
            name='TravelInsuranceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=50, verbose_name='No.')),
                ('emp_code', models.CharField(max_length=50, verbose_name='Employee Code')),
                ('job_level', models.CharField(max_length=50, verbose_name='Job Level')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Amount')),
                ('transaction_date', models.DateField(auto_now=True, verbose_name='Transaction Date')),
                ('no_series', models.CharField(max_length=50, verbose_name='No. Series')),
                ('posted', models.BooleanField(verbose_name='Posted')),
                ('trip', models.CharField(max_length=50, verbose_name='Trip')),
                ('purpose', models.TextField(verbose_name='Purpose')),
                ('start_date', models.DateField(auto_now=True, verbose_name='Start Date')),
                ('end_date', models.DateField(auto_now=True, verbose_name='End Date')),
                ('department_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.department', verbose_name='Department Code')),
                ('emp_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='Employee Name')),
                ('job_title_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.job', verbose_name='Job Title Code')),
            ],
            options={
                'verbose_name': 'Travel Insurance Entry',
                'verbose_name_plural': 'Travel Insurance Entries',
            },
        ),
    ]
