# Generated by Django 4.1.7 on 2023-02-21 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0003_initial'),
        ('insuranceapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelinsuranceentry',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User ID'),
        ),
        migrations.AddField(
            model_name='insurancepremiumpayments',
            name='company_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='Company Name'),
        ),
        migrations.AddField(
            model_name='insurancepremiumpayments',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User ID'),
        ),
        migrations.AddField(
            model_name='grouplifeinsurance',
            name='name_of_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='Name Of Company'),
        ),
        migrations.AddField(
            model_name='groupinsurancebeneficiaries',
            name='department_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.department', verbose_name='Department Code'),
        ),
        migrations.AddField(
            model_name='groupinsurancebeneficiaries',
            name='emp_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='Employee Name'),
        ),
        migrations.AddField(
            model_name='groupinsurancebeneficiaries',
            name='job_title_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.job', verbose_name='Job Title Code'),
        ),
        migrations.AddField(
            model_name='groupinsurancebeneficiaries',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User ID'),
        ),
    ]
