# Generated by Django 4.1.7 on 2023-02-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCenters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
                ('address2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Address 2')),
                ('contact_number', models.CharField(max_length=50, verbose_name='Contact Number')),
                ('contact_person', models.CharField(max_length=200, verbose_name='Contact Person')),
                ('blocked', models.BooleanField(verbose_name='Blocked')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, verbose_name='Description')),
                ('limit_type', models.CharField(choices=[('NO LIMIT', 'No Limit'), ('PER VISIT', 'Per Visit'), ('Annual', 'Annual')], max_length=50, verbose_name='Limit Type')),
                ('medical_limit', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Medical Limit')),
                ('blocked', models.BooleanField(verbose_name='Blocked')),
            ],
            options={
                'verbose_name': 'Medical Code',
                'verbose_name_plural': 'Medical Codes',
            },
        ),
    ]
