# Generated by Django 4.1.7 on 2023-02-21 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0002_initial'),
        ('employee', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workmencompensation',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User ID'),
        ),
        migrations.AddField(
            model_name='travels',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User ID'),
        ),
        migrations.AddField(
            model_name='travelexpenses',
            name='travel_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.travels', verbose_name='Travel No'),
        ),
        migrations.AddField(
            model_name='qualificationmetricsqef',
            name='minimum_qualification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.minimumqualification', verbose_name='Minimum Qualification'),
        ),
        migrations.AddField(
            model_name='propertyassignment',
            name='asset_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.property', verbose_name='Asset Code'),
        ),
        migrations.AddField(
            model_name='propertyassignment',
            name='emp_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='Employee Name'),
        ),
        migrations.AddField(
            model_name='propertyassignment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User ID'),
        ),
        migrations.AddField(
            model_name='performanceoverview',
            name='emp_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='Employee Code'),
        ),
        migrations.AddField(
            model_name='passportissues',
            name='emp_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='Employee Name'),
        ),
        migrations.AddField(
            model_name='passportissues',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User ID'),
        ),
        migrations.AddField(
            model_name='organizationalstructure',
            name='department_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.department', verbose_name='Department Code'),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='department_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.department', verbose_name='Department Name'),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='job_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.job', verbose_name='Job Title'),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='min_qualification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.minimumqualification', verbose_name='Minimum Qualification'),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User ID'),
        ),
        migrations.AddField(
            model_name='jobapplicationqualification',
            name='publication_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.jobopening', verbose_name='Publication No.'),
        ),
        migrations.AddField(
            model_name='jobapplicationqualification',
            name='qualification_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.minimumqualification', verbose_name='Qualification Code'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='publication_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.jobopening', verbose_name='Publication No.'),
        ),
        migrations.AddField(
            model_name='job',
            name='comp_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='Company Code'),
        ),
        migrations.AddField(
            model_name='hrneedsline',
            name='job_title_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.job', verbose_name='Job Title Code'),
        ),
        migrations.AddField(
            model_name='hrapprovalentry',
            name='last_modified_by_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='hralerts',
            name='emp_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='Employee Code'),
        ),
        migrations.AddField(
            model_name='hralerts',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User ID'),
        ),
        migrations.AddField(
            model_name='hospitalityservices',
            name='hospitality_facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.hospitalityfacilities', verbose_name=''),
        ),
        migrations.AddField(
            model_name='hospitalityservices',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='grievanceline',
            name='header_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.grievanceheader', verbose_name='Header No.'),
        ),
        migrations.AddField(
            model_name='grievanceheader',
            name='department_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.department', verbose_name='Department Code'),
        ),
        migrations.AddField(
            model_name='grievanceheader',
            name='emp_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='Employee Code'),
        ),
        migrations.AddField(
            model_name='grievanceentry',
            name='department_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.department', verbose_name='Department Name'),
        ),
        migrations.AddField(
            model_name='grievanceentry',
            name='employee_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='Employee Name'),
        ),
        migrations.AddField(
            model_name='grievanceentry',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User ID'),
        ),
        migrations.AddField(
            model_name='expatriates',
            name='company_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='Company Code'),
        ),
        migrations.AddField(
            model_name='expatriates',
            name='job_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.job', verbose_name='Job Code'),
        ),
        migrations.AddField(
            model_name='expatriateapplication',
            name='expatriate_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.expatriates', verbose_name='Expatriate No.'),
        ),
        migrations.AddField(
            model_name='endofserviceentry',
            name='department_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.department', verbose_name='Department Code'),
        ),
        migrations.AddField(
            model_name='endofserviceentry',
            name='emp_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='Employee Name'),
        ),
        migrations.AddField(
            model_name='endofserviceentry',
            name='job_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.job', verbose_name='Job Title'),
        ),
        migrations.AddField(
            model_name='endofserviceentry',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User ID'),
        ),
        migrations.AddField(
            model_name='courierservicerequisition',
            name='requesting_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.department', verbose_name='Requesting Department'),
        ),
        migrations.AddField(
            model_name='courierservicerequisition',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User ID'),
        ),
        migrations.AddField(
            model_name='companystaffbreakdown',
            name='company_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='Company Code'),
        ),
        migrations.AddField(
            model_name='companystaffbreakdown',
            name='field_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companyfield', verbose_name='Field Code'),
        ),
        migrations.AddField(
            model_name='company',
            name='comp_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='company.companytype', verbose_name='Company Type'),
        ),
        migrations.AddField(
            model_name='collectivebargaining',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User ID'),
        ),
        migrations.AddField(
            model_name='cashbenefitpayments',
            name='department_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.department', verbose_name='Department Code'),
        ),
        migrations.AddField(
            model_name='cashbenefitpayments',
            name='emp_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='Employee Name'),
        ),
        migrations.AddField(
            model_name='cashbenefitpayments',
            name='job_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.job', verbose_name='Job Title'),
        ),
        migrations.AddField(
            model_name='cashbenefitpayments',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User ID'),
        ),
        migrations.AddField(
            model_name='applicationpool',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User ID'),
        ),
    ]
