# Generated by Django 4.1.7 on 2023-02-21 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0002_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=50, verbose_name='Employee Name')),
                ('division', models.CharField(max_length=50, verbose_name='Division')),
                ('department', models.CharField(max_length=50, verbose_name='Department')),
                ('reports_to_code', models.CharField(max_length=50, verbose_name='ReportTo Code')),
                ('reports_to', models.CharField(max_length=150, verbose_name='Reports To')),
                ('job_purpose', models.CharField(max_length=50, verbose_name='Job Purpose')),
                ('prepared_by', models.CharField(max_length=50, verbose_name='Prepared By')),
                ('date', models.DateField(verbose_name='Date')),
                ('transaction_date', models.DateField(verbose_name='Transaction Date')),
                ('no_series_code', models.CharField(max_length=50, verbose_name='No. Series')),
                ('posted', models.BooleanField(verbose_name='Posted')),
            ],
            options={
                'verbose_name': 'Job Analysis',
                'verbose_name_plural': 'Job Analysises',
            },
        ),
        migrations.CreateModel(
            name='JobAnalysisAuthorityLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_no', models.PositiveIntegerField(verbose_name='Entry No.')),
                ('authority_type', models.CharField(max_length=50, verbose_name='Authority Type')),
                ('authority_limit', models.CharField(max_length=50, verbose_name='Authority Limit')),
            ],
            options={
                'verbose_name': 'Job Analysis Authority Limit',
                'verbose_name_plural': 'Job Analysis Authority Limits',
            },
        ),
        migrations.CreateModel(
            name='JobAnalysisContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.PositiveIntegerField(verbose_name='Entry')),
                ('contact_type', models.CharField(choices=[('INTERNAL', 'Internal'), ('EXTERNAL', 'External')], max_length=50, verbose_name='Contact Type')),
                ('contact_person', models.CharField(max_length=50, verbose_name='Contact Person')),
                ('position', models.CharField(max_length=50, verbose_name='Position')),
                ('contact_no', models.CharField(max_length=50, verbose_name='Contact Number')),
            ],
            options={
                'verbose_name': 'Job Analysis Contact',
                'verbose_name_plural': 'Job Analysis Contacts',
            },
        ),
        migrations.CreateModel(
            name='JobAnalysisDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.PositiveIntegerField(verbose_name='Entry No.')),
                ('type', models.CharField(choices=[('PHYSICAL WORK ENVIRONMENT', 'Physical Work Environment'), ('PHYSICAL EFFORT', 'Physical Effort'), ('Psychological Demands', 'Psychological Demands')], max_length=50, verbose_name='Demand Type')),
                ('description', models.CharField(max_length=50, verbose_name='Demand Description')),
            ],
            options={
                'verbose_name': 'Job Analysis Demand',
                'verbose_name_plural': 'Job Analysis Demands',
            },
        ),
        migrations.CreateModel(
            name='JobAnalysisDuties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_no', models.PositiveIntegerField(verbose_name='Entry Number')),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUALLY', 'Annually'), ('IRREGULAR', 'Irregular'), ('INTERVAL', 'Interval'), ('OTHER', 'Other')], max_length=50, verbose_name='Frequency')),
                ('duties', models.CharField(max_length=50, verbose_name='Duties')),
                ('responsibilities', models.CharField(max_length=50, verbose_name='Responsibilities')),
                ('adr', models.CharField(max_length=50, verbose_name='Action/Decision/Resources')),
            ],
            options={
                'verbose_name': 'Job Analysis Duties',
                'verbose_name_plural': 'Job Analysis Duties',
            },
        ),
        migrations.CreateModel(
            name='JobAnalysisRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_no', models.PositiveIntegerField(verbose_name='Entry No.')),
                ('type', models.CharField(choices=[('QUALIFICATION', 'Qualification'), ('MINIMUM EXPERIENCE', 'Minimum Experience'), ('TECHNICAL COMPETENCIES', 'Technical Competencies'), ('MANAGERIAL COMPETENCIES', 'Managerial Competencies'), ('PERSONAL COMPETENCIES', 'Personal Competencies')], max_length=50, verbose_name='Requirement Type')),
                ('description', models.CharField(max_length=50, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Job Analysis Requirement',
                'verbose_name_plural': 'Job Analysis Requirements',
            },
        ),
        migrations.CreateModel(
            name='JobAnalysisSupervision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_no', models.PositiveIntegerField(verbose_name='Entry Number')),
                ('supervision_type', models.CharField(choices=[('SUPERVISION GIVEN', 'Supervision Given'), ('SUPERVISION RECEIVED', 'Supervision Received')], max_length=50, verbose_name='Supervision Type')),
                ('supervision_detail', models.CharField(max_length=50, verbose_name='Supervision Details')),
            ],
            options={
                'verbose_name': 'Job Analysis Supervision',
                'verbose_name_plural': 'Job Analysis Supervisiond',
            },
        ),
        migrations.CreateModel(
            name='JobRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_no', models.PositiveIntegerField(verbose_name='Entry No.')),
                ('type', models.CharField(max_length=50, verbose_name='Requirement Type')),
                ('job_analysis_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobanalysis.jobanalysis', verbose_name='Job Analysis code')),
            ],
        ),
        migrations.CreateModel(
            name='JobEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_no', models.PositiveIntegerField(verbose_name='Entry No.')),
                ('emp_name', models.CharField(max_length=50, verbose_name='Employee Name')),
                ('department', models.CharField(max_length=50, verbose_name='Department')),
                ('current_job_level', models.CharField(max_length=50, verbose_name='Current Job Level')),
                ('current_pay_range', models.PositiveIntegerField(verbose_name='Current Pay Range')),
                ('new_job_level', models.CharField(max_length=50, verbose_name='New Job Level')),
                ('new_pay_range', models.PositiveIntegerField(verbose_name='New Pay Range')),
                ('transaction_date', models.DateField(verbose_name='Transaction Code')),
                ('posted', models.BooleanField(verbose_name='Posted')),
                ('emp_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='')),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.job', verbose_name='Job Title')),
            ],
            options={
                'verbose_name': 'Job Evaluation',
                'verbose_name_plural': 'Job Evaluations',
            },
        ),
    ]
