# Generated by Django 4.1.7 on 2023-02-21 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0003_initial'),
        ('jobanalysis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobevaluation',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=''),
        ),
        migrations.AddField(
            model_name='jobanalysissupervision',
            name='job_analysis_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobanalysis.jobanalysis', verbose_name='Job Analysis code'),
        ),
        migrations.AddField(
            model_name='jobanalysisrequirement',
            name='job_analysis_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobanalysis.jobanalysis', verbose_name='Job Analysis'),
        ),
        migrations.AddField(
            model_name='jobanalysisduties',
            name='job_analysis_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobanalysis.jobanalysis', verbose_name='Job Analysis code'),
        ),
        migrations.AddField(
            model_name='jobanalysisdemand',
            name='job_analysis_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobanalysis.jobanalysis', verbose_name='Job Analysis No.'),
        ),
        migrations.AddField(
            model_name='jobanalysiscontact',
            name='job_analysis_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobanalysis.jobanalysis', verbose_name='Job Analysis No.'),
        ),
        migrations.AddField(
            model_name='jobanalysisauthoritylimit',
            name='job_analysis_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobanalysis.jobanalysis', verbose_name='Job Analysis'),
        ),
        migrations.AddField(
            model_name='jobanalysis',
            name='emp_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='Employee Code'),
        ),
        migrations.AddField(
            model_name='jobanalysis',
            name='job_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobtitle', to='company.job', verbose_name=''),
        ),
        migrations.AddField(
            model_name='jobanalysis',
            name='job_title_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobcode', to='company.job', verbose_name=''),
        ),
        migrations.AddField(
            model_name='jobanalysis',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=''),
        ),
    ]
