# Generated by Django 4.1.7 on 2023-02-21 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_no', models.PositiveIntegerField(verbose_name='Test No.')),
                ('medical_test', models.CharField(max_length=150, verbose_name='Medical Test')),
                ('publication_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.jobopening', verbose_name='Publication No.')),
            ],
            options={
                'verbose_name': 'Medical Questionnaire',
                'verbose_name_plural': 'Medical Questionnaires',
            },
        ),
        migrations.CreateModel(
            name='InterviewTestQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveIntegerField(verbose_name='Weight')),
                ('minimum_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Minimum Score')),
                ('maximum_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Maximum Score')),
                ('line_no', models.PositiveIntegerField(verbose_name='Line No.')),
                ('question', models.CharField(max_length=150, verbose_name='Question')),
                ('publication_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.jobopening', verbose_name='Publication No.')),
            ],
            options={
                'verbose_name': 'Interview/Test Questionnaire',
                'verbose_name_plural': 'Interview/Test Questionnaires',
            },
        ),
        migrations.CreateModel(
            name='InterviewScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveIntegerField(verbose_name='Weight')),
                ('minimum_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Minimum Score')),
                ('maximum_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Maximum Score')),
                ('entry_no', models.PositiveIntegerField(verbose_name='Entry No')),
                ('question_no', models.PositiveIntegerField(verbose_name='Question No.')),
                ('question', models.CharField(max_length=150, verbose_name='Question')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Score')),
                ('weight_average_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Weighted Average Score')),
                ('publication_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.jobopening', verbose_name='Publication Code')),
            ],
            options={
                'verbose_name': 'Interview / Test Score',
                'verbose_name_plural': 'Interview / Test Scores',
            },
        ),
        migrations.CreateModel(
            name='InterviewPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_no', models.CharField(max_length=50, verbose_name='Interview No.')),
                ('entry_no', models.PositiveIntegerField(verbose_name='Entry No.')),
                ('interviewer_name', models.CharField(max_length=150, verbose_name='Interviewer Name')),
                ('job_title', models.CharField(max_length=50, verbose_name='Job Title')),
                ('emp_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='Employee Code')),
                ('job_title_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.job', verbose_name='Job Title Code')),
            ],
            options={
                'verbose_name': 'Interview Panel',
                'verbose_name_plural': 'Interview Panels',
            },
        ),
        migrations.CreateModel(
            name='ApplicantMedicalTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_no', models.PositiveIntegerField(verbose_name='Entry No.')),
                ('test_no', models.PositiveIntegerField(verbose_name='Test No.')),
                ('medical_test', models.CharField(max_length=150, verbose_name='Medical Test')),
                ('passed', models.BooleanField(verbose_name='Passed')),
                ('publication_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.jobopening', verbose_name='Publication No.')),
            ],
            options={
                'verbose_name': 'Applicant Medical Test',
                'verbose_name_plural': 'Applicant Medical Tests',
            },
        ),
    ]
